package com.quizz.entities;
// Generated Feb 20, 2025, 8:41:28 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Answers generated by hbm2java
 */
@Entity
@Table(name = "answers")
public class Answers implements java.io.Serializable {

    private Long answerId;
    private Questions questions;
    private String answerText;
    private Boolean isCorrect;
    private Integer orderIndex;
    private Date createdAt;
    private Date deletedAt;
    private List<UserAnswers> userAnswerses = new ArrayList<UserAnswers>(0);

    public Answers() {
    }

    public Answers(String answerText) {
	this.answerText = answerText;
    }

    public Answers(Questions questions, String answerText, Boolean isCorrect, Integer orderIndex, Date createdAt,
	    Date deletedAt, List<UserAnswers> userAnswerses) {
	this.questions = questions;
	this.answerText = answerText;
	this.isCorrect = isCorrect;
	this.orderIndex = orderIndex;
	this.createdAt = createdAt;
	this.deletedAt = deletedAt;
	this.userAnswerses = userAnswerses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "answer_id", unique = true, nullable = false)
    public Long getAnswerId() {
	return this.answerId;
    }

    public void setAnswerId(Long answerId) {
	this.answerId = answerId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "question_id")
    public Questions getQuestions() {
	return this.questions;
    }

    public void setQuestions(Questions questions) {
	this.questions = questions;
    }

    @Column(name = "answer_text", nullable = false, length = 65535)
    public String getAnswerText() {
	return this.answerText;
    }

    public void setAnswerText(String answerText) {
	this.answerText = answerText;
    }

    @Column(name = "is_correct")
    public Boolean getIsCorrect() {
	return this.isCorrect;
    }

    public void setIsCorrect(Boolean isCorrect) {
	this.isCorrect = isCorrect;
    }

    @Column(name = "order_index")
    public Integer getOrderIndex() {
	return this.orderIndex;
    }

    public void setOrderIndex(Integer orderIndex) {
	this.orderIndex = orderIndex;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", length = 19)
    public Date getCreatedAt() {
	return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
	this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "deleted_at", length = 19)
    public Date getDeletedAt() {
	return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
	this.deletedAt = deletedAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "answers")
    public List<UserAnswers> getUserAnswerses() {
	return this.userAnswerses;
    }

    public void setUserAnswerses(List<UserAnswers> userAnswerses) {
	this.userAnswerses = userAnswerses;
    }

}
