package com.quizz.entities;
// Generated Feb 20, 2025, 8:41:28 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories")
public class Categories implements java.io.Serializable {

    private Long categoryId;
    private String name;
    private String description;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;
    private List<Quizzes> quizzeses = new ArrayList<Quizzes>(0);

    public Categories() {
    }

    public Categories(String name) {
	this.name = name;
    }

    public Categories(String name, String description, Date createdAt, Date updatedAt, Date deletedAt,
	    List<Quizzes> quizzeses) {
	this.name = name;
	this.description = description;
	this.createdAt = createdAt;
	this.updatedAt = updatedAt;
	this.deletedAt = deletedAt;
	this.quizzeses = quizzeses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "category_id", unique = true, nullable = false)
    public Long getCategoryId() {
	return this.categoryId;
    }

    public void setCategoryId(Long categoryId) {
	this.categoryId = categoryId;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "description", length = 65535)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", length = 19)
    public Date getCreatedAt() {
	return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
	this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", length = 19)
    public Date getUpdatedAt() {
	return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
	this.updatedAt = updatedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "deleted_at", length = 19)
    public Date getDeletedAt() {
	return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
	this.deletedAt = deletedAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
    public List<Quizzes> getQuizzeses() {
	return this.quizzeses;
    }

    public void setQuizzeses(List<Quizzes> quizzeses) {
	this.quizzeses = quizzeses;
    }

}
