package com.quizz.entities;
// Generated Feb 20, 2025, 8:41:28 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * QuizzAttempts generated by hbm2java
 */
@Entity
@Table(name = "quizz_attempts")
public class QuizzAttempts implements java.io.Serializable {

    private Long attemptId;
    private Quizzes quizzes;
    private Users users;
    private Date startTime;
    private Date endTime;
    private Integer score;
    private String status;
    private Date createdAt;
    private List<UserAnswers> userAnswerses = new ArrayList<UserAnswers>(0);

    public QuizzAttempts() {
    }

    public QuizzAttempts(Date startTime) {
	this.startTime = startTime;
    }

    public QuizzAttempts(Quizzes quizzes, Users users, Date startTime, Date endTime, Integer score, String status,
	    Date createdAt, List<UserAnswers> userAnswerses) {
	this.quizzes = quizzes;
	this.users = users;
	this.startTime = startTime;
	this.endTime = endTime;
	this.score = score;
	this.status = status;
	this.createdAt = createdAt;
	this.userAnswerses = userAnswerses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "attempt_id", unique = true, nullable = false)
    public Long getAttemptId() {
	return this.attemptId;
    }

    public void setAttemptId(Long attemptId) {
	this.attemptId = attemptId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "quizz_id")
    public Quizzes getQuizzes() {
	return this.quizzes;
    }

    public void setQuizzes(Quizzes quizzes) {
	this.quizzes = quizzes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    public Users getUsers() {
	return this.users;
    }

    public void setUsers(Users users) {
	this.users = users;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time", nullable = false, length = 19)
    public Date getStartTime() {
	return this.startTime;
    }

    public void setStartTime(Date startTime) {
	this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time", length = 19)
    public Date getEndTime() {
	return this.endTime;
    }

    public void setEndTime(Date endTime) {
	this.endTime = endTime;
    }

    @Column(name = "score")
    public Integer getScore() {
	return this.score;
    }

    public void setScore(Integer score) {
	this.score = score;
    }

    @Column(name = "status", length = 20)
    public String getStatus() {
	return this.status;
    }

    public void setStatus(String status) {
	this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", length = 19)
    public Date getCreatedAt() {
	return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
	this.createdAt = createdAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "quizzAttempts")
    public List<UserAnswers> getUserAnswerses() {
	return this.userAnswerses;
    }

    public void setUserAnswerses(List<UserAnswers> userAnswerses) {
	this.userAnswerses = userAnswerses;
    }

}
